# Generated by Django 4.2 on 2024-08-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='image',
            field=models.ImageField(upload_to='static/Songs-Template/'),
        ),
        migrations.AlterField(
            model_name='songinfo',
            name='song',
            field=models.FileField(upload_to='static/Audio_Files/'),
        ),
    ]
