# Generated by Django 4.2 on 2024-08-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_songinfo_image_alter_songinfo_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinfo',
            name='image',
            field=models.ImageField(upload_to='Songs-Template/'),
        ),
        migrations.AlterField(
            model_name='songinfo',
            name='song',
            field=models.FileField(upload_to='Audio_Files/'),
        ),
    ]
